=== ExpertRootGroup/er/macro/BeamDet/equip.dtd
<!ELEMENT BeamDetParts (ToFTypes, MWPCTypes)>
<!ELEMENT ToFTypes (ToF+)>
<!ELEMENT ToF (plasticGeometry, plasticMedia)>
<!ATTLIST ToF
  id ID #REQUIRED
>
<!ELEMENT plasticGeometry EMPTY>
<!ATTLIST plasticGeometry
  X CDATA #REQUIRED
  Y CDATA #REQUIRED
  Z CDATA #REQUIRED
>
<!ELEMENT plasticMedia (#PCDATA)>

<!ELEMENT MWPCTypes (MWPC+)>
<!ELEMENT MWPC (gasVolGeometry,gasStripGeometry, distBetweenXandYStrips, aluminiumThickness, kaptonThickness, wireDiameter, kaptonMedia, aluminiumMedia, tungstenMedia, gasMedia)> 
<!ATTLIST MWPC
  id ID #REQUIRED
> 
<!ELEMENT gasVolGeometry EMPTY>
<!ATTLIST gasVolGeometry
  X CDATA #REQUIRED
  Y CDATA #REQUIRED
  Z CDATA #REQUIRED
>
<!ELEMENT gasStripGeometry EMPTY>
<!ATTLIST gasStripGeometry
  X CDATA #REQUIRED
  Y CDATA #REQUIRED
  Z CDATA #REQUIRED
>
<!ELEMENT distBetweenXandYStrips (#PCDATA)>
<!ELEMENT aluminiumThickness (#PCDATA)>
<!ELEMENT kaptonThickness (#PCDATA)>
<!ELEMENT wireDiameter (#PCDATA)>
<!ELEMENT kaptonMedia (#PCDATA)>
<!ELEMENT aluminiumMedia (#PCDATA)>
<!ELEMENT tungstenMedia (#PCDATA)>
<!ELEMENT gasMedia (#PCDATA)>

=== ExpertRootGroup/er/macro/BeamDet/equip.xml
<?xml version = "1.0" encoding = "utf-8" ?>
<!DOCTYPE BeamDetParts SYSTEM "equip.dtd">
<BeamDetParts>
  <ToFTypes>
    <ToF id = "ToF1">
      <plasticGeometry X = "100" Y = "100" Z = "0.01"/>
      <plasticMedia>BC408</plasticMedia>
    </ToF>
  </ToFTypes>
  <MWPCTypes>
    <MWPC id = "MWPC1">
      <gasVolGeometry   X = "5."    Y = "5." Z = "8.2"/>
      <gasStripGeometry X = "0.125" Y = "5." Z = "0.6"/>
      <distBetweenXandYStrips>1</distBetweenXandYStrips>
      <aluminiumThickness>5 * 1e-4</aluminiumThickness>
      <kaptonThickness>12.5 * 1e-4</kaptonThickness>
      <wireDiameter>20 * 1e-4</wireDiameter>
      <kaptonMedia>kapton</kaptonMedia>
      <aluminiumMedia>aluminium</aluminiumMedia>
      <tungstenMedia>tungsten</tungstenMedia>
      <gasMedia>CF4_CH4</gasMedia>
    </MWPC>
  </MWPCTypes>
</BeamDetParts>
